#include "breadboard.h"
#include "page.h"

typedef struct {
  const PageLine *lines;
  int line_count;
} PartInfo;

static const PageLine WIRE_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A jumper wire joins two holes as if"},
  {PAGE_LINE_TEXT, NULL, "they were one."},
  {PAGE_LINE_TEXT, NULL, "Its color changes with each wire."},
  {PAGE_LINE_TEXT, NULL, "In the game, only wires may go on"},
  {PAGE_LINE_TEXT, NULL, "the rails."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "end - both ends are the same."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Wire / passive."},
  {PAGE_LINE_TEXT, NULL, "Enter on one hole, then move and"},
  {PAGE_LINE_TEXT, NULL, "Enter on the other."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
};

static const PageLine RESISTOR_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A resistor limits current. The"},
  {PAGE_LINE_TEXT, NULL, "bigger its value, the less current"},
  {PAGE_LINE_TEXT, NULL, "flows. It has no direction."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "lead - either way round."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Wire / passive."},
  {PAGE_LINE_TEXT, NULL, "Enter on one hole, then move and"},
  {PAGE_LINE_TEXT, NULL, "Enter on the other."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "+", "next bigger value"},
  {PAGE_LINE_KEY, "-", "next smaller value"},
  {PAGE_LINE_TEXT, NULL, "Values: 10, 100, 220, 330, 470,"},
  {PAGE_LINE_TEXT, NULL, "1k, 2.2k, 4.7k, 10k, 100k ohm."},
  {PAGE_LINE_TEXT, NULL, "It starts at 220 ohm."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "Its value and current, e.g."},
  {PAGE_LINE_TEXT, NULL, "220ohm 13mA."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Put one in series with each LED."},
  {PAGE_LINE_TEXT, NULL, "A red LED on 5V lights safely with"},
  {PAGE_LINE_TEXT, NULL, "100 ohm to 4.7k."},
};

static const PageLine LED_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A light that glows when current"},
  {PAGE_LINE_TEXT, NULL, "flows from anode+ to cathode-."},
  {PAGE_LINE_TEXT, NULL, "The voltage it takes: red 1.8V,"},
  {PAGE_LINE_TEXT, NULL, "yellow 2.0V, green 2.1V, blue 3.0V."},
  {PAGE_LINE_TEXT, NULL, "It glows from 0.5mA, fully at 20mA,"},
  {PAGE_LINE_TEXT, NULL, "and burns out above 50mA."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "anode+ - toward battery +."},
  {PAGE_LINE_TEXT, NULL, "cathode- - toward battery -."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: LED / display."},
  {PAGE_LINE_TEXT, NULL, "Enter on the hole for anode+, then"},
  {PAGE_LINE_TEXT, NULL, "move and Enter for cathode-."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The current through it, or BURNED."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Always add a resistor in series:"},
  {PAGE_LINE_TEXT, NULL, "straight on 5V it burns out."},
  {PAGE_LINE_TEXT, NULL, "Put in backwards, it stays dark."},
  {PAGE_LINE_TEXT, NULL, "A burned LED never lights again."},
  {PAGE_LINE_TEXT, NULL, "In the game, a burned LED ends it."},
};

static const PageLine RGB_LED_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "Three LEDs (red, green, blue) in"},
  {PAGE_LINE_TEXT, NULL, "one case, sharing common-."},
  {PAGE_LINE_TEXT, NULL, "Red takes 1.8V, green and blue 3.0V."},
  {PAGE_LINE_TEXT, NULL, "Each color glows from 0.5mA, fully"},
  {PAGE_LINE_TEXT, NULL, "at 20mA, and burns above 50mA."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Four in a row, left to right:"},
  {PAGE_LINE_TEXT, NULL, "red, common-, green, blue."},
  {PAGE_LINE_TEXT, NULL, "common- goes toward battery -."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: LED / display."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its left"},
  {PAGE_LINE_TEXT, NULL, "pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The total current of all colors,"},
  {PAGE_LINE_TEXT, NULL, "or BURNED."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Give each color its own resistor."},
  {PAGE_LINE_TEXT, NULL, "In the game, a burned LED ends it."},
};

static const PageLine SEVEN_SEGMENT_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "Eight red LEDs (a-g and dp) that"},
  {PAGE_LINE_TEXT, NULL, "draw a digit. All share common-."},
  {PAGE_LINE_TEXT, NULL, "Each segment takes 1.8V, glows from"},
  {PAGE_LINE_TEXT, NULL, "0.5mA, fully at 20mA, and burns"},
  {PAGE_LINE_TEXT, NULL, "above 50mA."},
  {PAGE_LINE_TEXT, NULL, "a top, b top right, c bottom right,"},
  {PAGE_LINE_TEXT, NULL, "d bottom, e bottom left, f top"},
  {PAGE_LINE_TEXT, NULL, "left, g middle, dp dot."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Top row, left to right:"},
  {PAGE_LINE_TEXT, NULL, "g, f, common-, a, b."},
  {PAGE_LINE_TEXT, NULL, "Bottom row, 3 holes lower:"},
  {PAGE_LINE_TEXT, NULL, "e, d, common-, c, dp."},
  {PAGE_LINE_TEXT, NULL, "The two common- pins are joined."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: LED / display."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its top-"},
  {PAGE_LINE_TEXT, NULL, "left pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The total current of all segments,"},
  {PAGE_LINE_TEXT, NULL, "or BURNED."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Give each segment its own"},
  {PAGE_LINE_TEXT, NULL, "resistor."},
  {PAGE_LINE_TEXT, NULL, "In the game, a burned one ends it."},
};

static const PageLine DIODE_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "Lets current flow only from anode+"},
  {PAGE_LINE_TEXT, NULL, "to cathode-. It takes 0.7V."},
  {PAGE_LINE_TEXT, NULL, "It gives no light and never burns."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "anode+ - where current goes in."},
  {PAGE_LINE_TEXT, NULL, "cathode- - where it comes out."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Semiconductor."},
  {PAGE_LINE_TEXT, NULL, "Enter on the hole for anode+, then"},
  {PAGE_LINE_TEXT, NULL, "move and Enter for cathode-."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The current through it."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Use it to stop current going the"},
  {PAGE_LINE_TEXT, NULL, "wrong way."},
};

static const PageLine TACT_SWITCH_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A push button. While pressed, it"},
  {PAGE_LINE_TEXT, NULL, "joins its left and right pins."},
  {PAGE_LINE_TEXT, NULL, "It lets go by itself."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Four pins in two rows, the right"},
  {PAGE_LINE_TEXT, NULL, "ones 2 holes right of the left."},
  {PAGE_LINE_TEXT, NULL, "left - the two left pins, always"},
  {PAGE_LINE_TEXT, NULL, "joined to each other."},
  {PAGE_LINE_TEXT, NULL, "right - the two right pins, always"},
  {PAGE_LINE_TEXT, NULL, "joined to each other."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Switch."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its top-"},
  {PAGE_LINE_TEXT, NULL, "left pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "space", "press it for a moment"},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "pressed while held, else space."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Wire a left pin to one side of the"},
  {PAGE_LINE_TEXT, NULL, "circuit and a right pin to the"},
  {PAGE_LINE_TEXT, NULL, "other."},
};

static const PageLine SLIDE_SWITCH_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A switch that joins common to A or"},
  {PAGE_LINE_TEXT, NULL, "to B, and stays there."},
  {PAGE_LINE_TEXT, NULL, "It starts on A."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Three in a row, left to right:"},
  {PAGE_LINE_TEXT, NULL, "A, common, B."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Switch."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its left"},
  {PAGE_LINE_TEXT, NULL, "pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "space", "flip between A and B"},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "A side or B side."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Use it as an on / off switch with"},
  {PAGE_LINE_TEXT, NULL, "only A wired, or to pick one of"},
  {PAGE_LINE_TEXT, NULL, "two paths."},
};

static const PageLine BATTERY_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A 5V power source. Current flows"},
  {PAGE_LINE_TEXT, NULL, "out of +, through the circuit, and"},
  {PAGE_LINE_TEXT, NULL, "back into -."},
  {PAGE_LINE_TEXT, NULL, "In the game one sits on the top-"},
  {PAGE_LINE_TEXT, NULL, "left rails and none is dealt."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_KEY, "+", "5V side, to the red rail"},
  {PAGE_LINE_KEY, "-", "0V side, to the blue rail"},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Power / output."},
  {PAGE_LINE_TEXT, NULL, "Enter on the hole for +, then move"},
  {PAGE_LINE_TEXT, NULL, "and Enter for -."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "5.0V and the current it gives."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "More than 2A is a short: + joined"},
  {PAGE_LINE_TEXT, NULL, "to - with nothing in between. The"},
  {PAGE_LINE_TEXT, NULL, "header shows SHORT!, and in the"},
  {PAGE_LINE_TEXT, NULL, "game it is over."},
};

static const PageLine BUZZER_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "Sounds when current flows from +"},
  {PAGE_LINE_TEXT, NULL, "to -. The sound is shown as rings"},
  {PAGE_LINE_TEXT, NULL, "on screen; the speaker stays quiet."},
  {PAGE_LINE_TEXT, NULL, "It takes 1.0V, sounds above 5mA,"},
  {PAGE_LINE_TEXT, NULL, "and is loudest from 25mA."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_KEY, "+", "toward battery +"},
  {PAGE_LINE_KEY, "-", "toward battery -"},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Power / output."},
  {PAGE_LINE_TEXT, NULL, "Enter on the hole for +, then move"},
  {PAGE_LINE_TEXT, NULL, "and Enter for -."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The current through it."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Straight on 5V it is loudest; it"},
  {PAGE_LINE_TEXT, NULL, "needs no resistor."},
  {PAGE_LINE_TEXT, NULL, "Put in backwards, it stays quiet."},
};

static const PageLine MOTOR_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "Turns when current flows: the more"},
  {PAGE_LINE_TEXT, NULL, "current, the faster. Reverse the"},
  {PAGE_LINE_TEXT, NULL, "current to turn it the other way."},
  {PAGE_LINE_TEXT, NULL, "It is 25 ohm and needs 50mA to"},
  {PAGE_LINE_TEXT, NULL, "turn."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "lead - either way round."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Power / output."},
  {PAGE_LINE_TEXT, NULL, "Enter on one hole, then move and"},
  {PAGE_LINE_TEXT, NULL, "Enter on the other."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The current through it."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Straight on 5V it runs at full"},
  {PAGE_LINE_TEXT, NULL, "speed. With 100 ohm or more in"},
  {PAGE_LINE_TEXT, NULL, "series from 5V, it stops."},
};

static const PageLine NPN_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A transistor: a small current into"},
  {PAGE_LINE_TEXT, NULL, "base lets up to 100 times more flow"},
  {PAGE_LINE_TEXT, NULL, "from collector to emitter."},
  {PAGE_LINE_TEXT, NULL, "Base to emitter takes 0.7V."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Three in a row, left to right:"},
  {PAGE_LINE_TEXT, NULL, "emitter, base, collector."},
  {PAGE_LINE_TEXT, NULL, "emitter - toward battery -."},
  {PAGE_LINE_TEXT, NULL, "base - the control input."},
  {PAGE_LINE_TEXT, NULL, "collector - from the load."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Semiconductor."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its left"},
  {PAGE_LINE_TEXT, NULL, "pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "Ic: the collector current."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Put the load (LED, motor, relay)"},
  {PAGE_LINE_TEXT, NULL, "between + and collector, and"},
  {PAGE_LINE_TEXT, NULL, "emitter to -."},
  {PAGE_LINE_TEXT, NULL, "Feed the base through a resistor,"},
  {PAGE_LINE_TEXT, NULL, "e.g. 1k, from a switch or pino."},
};

static const PageLine RELAY_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A switch moved by a coil. With no"},
  {PAGE_LINE_TEXT, NULL, "coil current, common joins NC."},
  {PAGE_LINE_TEXT, NULL, "Over 30mA in the coil, common joins"},
  {PAGE_LINE_TEXT, NULL, "NO instead."},
  {PAGE_LINE_TEXT, NULL, "The coil is 100 ohm, so 5V straight"},
  {PAGE_LINE_TEXT, NULL, "across it turns it on."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Top row: coil, (gap), common."},
  {PAGE_LINE_TEXT, NULL, "Bottom row, 3 holes lower:"},
  {PAGE_LINE_TEXT, NULL, "coil, NC, NO."},
  {PAGE_LINE_TEXT, NULL, "coil - the two coil pins, either"},
  {PAGE_LINE_TEXT, NULL, "way round."},
  {PAGE_LINE_TEXT, NULL, "NC - joined to common when off."},
  {PAGE_LINE_TEXT, NULL, "NO - joined to common when on."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Switch."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its top-"},
  {PAGE_LINE_TEXT, NULL, "left pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "ON while the coil pulls, else OFF."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Drive the coil with a switch or an"},
  {PAGE_LINE_TEXT, NULL, "NPN transistor, and switch another"},
  {PAGE_LINE_TEXT, NULL, "circuit with common, NC and NO."},
};

static const PageLine VOLUME_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A 10k ohm variable resistor. The"},
  {PAGE_LINE_TEXT, NULL, "wiper slides along it: A-wiper and"},
  {PAGE_LINE_TEXT, NULL, "wiper-B always add up to 10k."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "Three in a row, left to right:"},
  {PAGE_LINE_TEXT, NULL, "A, wiper, B."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Wire / passive."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with its left"},
  {PAGE_LINE_TEXT, NULL, "pin at the cursor."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "+", "move the wiper 1k toward B"},
  {PAGE_LINE_KEY, "-", "move the wiper 1k toward A"},
  {PAGE_LINE_TEXT, NULL, "knob 0: wiper at A. 10: at B."},
  {PAGE_LINE_TEXT, NULL, "It starts at 5."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "knob n/10."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Use A and wiper alone as a 0-10k"},
  {PAGE_LINE_TEXT, NULL, "resistor, e.g. to dim an LED."},
  {PAGE_LINE_TEXT, NULL, "At knob 0 that is 0 ohm, so keep a"},
  {PAGE_LINE_TEXT, NULL, "fixed resistor in series too."},
};

static const PageLine CDS_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A light sensor: the more light,"},
  {PAGE_LINE_TEXT, NULL, "the lower its resistance. It has"},
  {PAGE_LINE_TEXT, NULL, "no direction."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "lead - either way round."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Wire / passive."},
  {PAGE_LINE_TEXT, NULL, "Enter on one hole, then move and"},
  {PAGE_LINE_TEXT, NULL, "Enter on the other."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "+", "more light"},
  {PAGE_LINE_KEY, "-", "less light"},
  {PAGE_LINE_TEXT, NULL, "Each step halves or doubles it."},
  {PAGE_LINE_TEXT, NULL, "light 0: 200k, 5: 6.25k, 10: 195"},
  {PAGE_LINE_TEXT, NULL, "ohm. It starts at 5."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "light n/10."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "In series with an LED, the LED"},
  {PAGE_LINE_TEXT, NULL, "gets brighter with more light."},
};

static const PageLine CAPACITOR_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A 1000uF capacitor stores charge."},
  {PAGE_LINE_TEXT, NULL, "It fills up through the circuit and"},
  {PAGE_LINE_TEXT, NULL, "gives the charge back later. The"},
  {PAGE_LINE_TEXT, NULL, "part shows how full it is."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_KEY, "+", "toward battery +"},
  {PAGE_LINE_KEY, "-", "toward battery -"},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Wire / passive."},
  {PAGE_LINE_TEXT, NULL, "Enter on the hole for +, then move"},
  {PAGE_LINE_TEXT, NULL, "and Enter for -."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_TEXT, NULL, "No key works on this part."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "The voltage across it."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "TIPS"},
  {PAGE_LINE_TEXT, NULL, "Through 1k it fills most of the"},
  {PAGE_LINE_TEXT, NULL, "way in about 1 second; 10k takes"},
  {PAGE_LINE_TEXT, NULL, "about 10."},
};

static const PageLine PINO_LINES[] = {
  {PAGE_LINE_HEADING, NULL, "WHAT IT IS"},
  {PAGE_LINE_TEXT, NULL, "A Raspberry Pi Pico for the board,"},
  {PAGE_LINE_TEXT, NULL, "programmed in PicoRuby."},
  {PAGE_LINE_TEXT, NULL, "Only one can be on the board. The"},
  {PAGE_LINE_TEXT, NULL, "game never deals it."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "POWER"},
  {PAGE_LINE_TEXT, NULL, "Wire battery + to VSYS (or VBUS)"},
  {PAGE_LINE_TEXT, NULL, "and battery - to GND. It is on"},
  {PAGE_LINE_TEXT, NULL, "while VSYS is 1.8V or more."},
  {PAGE_LINE_TEXT, NULL, "When power comes on, it runs"},
  {PAGE_LINE_TEXT, NULL, "Pin_data/app.rb."},
  {PAGE_LINE_TEXT, NULL, "Without power, 3V3(OUT), the GPIO"},
  {PAGE_LINE_TEXT, NULL, "pins and the LED are off and the"},
  {PAGE_LINE_TEXT, NULL, "program stops."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PINS"},
  {PAGE_LINE_TEXT, NULL, "USB end to the left. Pins 40-21 on"},
  {PAGE_LINE_TEXT, NULL, "the top row, 1-20 on the bottom."},
  {PAGE_LINE_TEXT, NULL, "VBUS - power in, on to VSYS through"},
  {PAGE_LINE_TEXT, NULL, "a diode."},
  {PAGE_LINE_TEXT, NULL, "VSYS - power in."},
  {PAGE_LINE_TEXT, NULL, "3V3(OUT) - 3.3V out while on."},
  {PAGE_LINE_TEXT, NULL, "GND / AGND - 0V, all joined."},
  {PAGE_LINE_TEXT, NULL, "GP0-GP22, GP26-GP28 - GPIO."},
  {PAGE_LINE_TEXT, NULL, "GP25 is the LED on the board."},
  {PAGE_LINE_TEXT, NULL, "GP24 reads 1 while VBUS has power."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "GPIO"},
  {PAGE_LINE_TEXT, NULL, "Output: 3.3V or 0V through 50 ohm."},
  {PAGE_LINE_TEXT, NULL, "All GPIO is off without power."},
  {PAGE_LINE_TEXT, NULL, "Pull-up / pull-down: 50k ohm."},
  {PAGE_LINE_TEXT, NULL, "Input reads 1 above 1.65V."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "PLACING"},
  {PAGE_LINE_TEXT, NULL, "Menu: Microcontroller."},
  {PAGE_LINE_TEXT, NULL, "One Enter drops it with pin 40 at"},
  {PAGE_LINE_TEXT, NULL, "the cursor. Put the cursor on row c"},
  {PAGE_LINE_TEXT, NULL, "so it straddles the groove."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "KEYS"},
  {PAGE_LINE_KEY, "e", "edit Pin_data/app.rb"},
  {PAGE_LINE_KEY, "v", "show its output"},
  {PAGE_LINE_TEXT, NULL, "Opening the editor stops the"},
  {PAGE_LINE_TEXT, NULL, "program; leaving it runs the"},
  {PAGE_LINE_TEXT, NULL, "program again if there is power."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "HEADER"},
  {PAGE_LINE_TEXT, NULL, "stopped, running, finished or"},
  {PAGE_LINE_TEXT, NULL, "error."},
  {PAGE_LINE_BLANK, NULL, NULL},
  {PAGE_LINE_HEADING, NULL, "EXAMPLE"},
  {PAGE_LINE_TEXT, NULL, "led = GPIO.new(15, GPIO::OUT)"},
  {PAGE_LINE_TEXT, NULL, "loop do"},
  {PAGE_LINE_TEXT, NULL, "  led.write(1)"},
  {PAGE_LINE_TEXT, NULL, "  sleep_ms 500"},
  {PAGE_LINE_TEXT, NULL, "  led.write(0)"},
  {PAGE_LINE_TEXT, NULL, "  sleep_ms 500"},
  {PAGE_LINE_TEXT, NULL, "end"},
};

static const PartInfo PART_INFOS[] = {
  [PART_KIND_WIRE] = {WIRE_LINES, COUNT_PAGE_LINES(WIRE_LINES)},
  [PART_KIND_RESISTOR] = {RESISTOR_LINES, COUNT_PAGE_LINES(RESISTOR_LINES)},
  [PART_KIND_LED] = {LED_LINES, COUNT_PAGE_LINES(LED_LINES)},
  [PART_KIND_RGB_LED] = {RGB_LED_LINES, COUNT_PAGE_LINES(RGB_LED_LINES)},
  [PART_KIND_SEVEN_SEGMENT] =
    {SEVEN_SEGMENT_LINES, COUNT_PAGE_LINES(SEVEN_SEGMENT_LINES)},
  [PART_KIND_DIODE] = {DIODE_LINES, COUNT_PAGE_LINES(DIODE_LINES)},
  [PART_KIND_TACT_SWITCH] =
    {TACT_SWITCH_LINES, COUNT_PAGE_LINES(TACT_SWITCH_LINES)},
  [PART_KIND_SLIDE_SWITCH] =
    {SLIDE_SWITCH_LINES, COUNT_PAGE_LINES(SLIDE_SWITCH_LINES)},
  [PART_KIND_BATTERY] = {BATTERY_LINES, COUNT_PAGE_LINES(BATTERY_LINES)},
  [PART_KIND_BUZZER] = {BUZZER_LINES, COUNT_PAGE_LINES(BUZZER_LINES)},
  [PART_KIND_MOTOR] = {MOTOR_LINES, COUNT_PAGE_LINES(MOTOR_LINES)},
  [PART_KIND_NPN] = {NPN_LINES, COUNT_PAGE_LINES(NPN_LINES)},
  [PART_KIND_RELAY] = {RELAY_LINES, COUNT_PAGE_LINES(RELAY_LINES)},
  [PART_KIND_VOLUME] = {VOLUME_LINES, COUNT_PAGE_LINES(VOLUME_LINES)},
  [PART_KIND_CDS] = {CDS_LINES, COUNT_PAGE_LINES(CDS_LINES)},
  [PART_KIND_CAPACITOR] = {CAPACITOR_LINES, COUNT_PAGE_LINES(CAPACITOR_LINES)},
  [PART_KIND_PINO] = {PINO_LINES, COUNT_PAGE_LINES(PINO_LINES)},
};

void
show_part_info(PartKind kind) {
  const PartInfo *info = &PART_INFOS[kind];

  show_page(find_part_name(kind), info->lines, info->line_count);
}
