#ifndef EDIT_MODE_H
#define EDIT_MODE_H

typedef enum {
  VIM_MODE_NORMAL = 0,
  VIM_MODE_OPERATOR,
  VIM_MODE_COMMAND,
  VIM_MODE_SEARCH,
  VIM_MODE_INSERT,
  VIM_MODE_VISUAL,
  VIM_MODE_VISUAL_LINE,
  VIM_MODE_VISUAL_BLOCK
} VimMode;

#endif
