
class Bool
  def !: () -> bool

  # Perform logical AND operation
  def &: (untyped other) -> bool

  def ===: (untyped other) -> bool

  # Perform logical XOR operation
  def ^: (untyped other) -> bool

  def to_s: () -> String

  # Perform logical OR operation
  def |: (untyped other) -> bool

end
