
class Math
  # Calculate arccosine
  def self.acos: (Float x) -> Float

  # Calculate inverse hyperbolic cosine
  def self.acosh: (Float x) -> Float

  # Calculate arcsine
  def self.asin: (Float x) -> Float

  # Calculate inverse hyperbolic sine
  def self.asinh: (Float x) -> Float

  # Calculate arctangent
  def self.atan: (Float x) -> Float

  # Calculate arctangent with two arguments
  def self.atan2: (Float y, Float x) -> Float

  # Calculate inverse hyperbolic tangent
  def self.atanh: (Float x) -> Float

  # Calculate cube root
  def self.cbrt: (Float x) -> Float

  # Calculate cosine
  def self.cos: (Float x) -> Float

  # Calculate hyperbolic cosine
  def self.cosh: (Float x) -> Float

  # Calculate error function
  def self.erf: (Float x) -> Float

  # Calculate complementary error function
  def self.erfc: (Float x) -> Float

  # Calculate exponential function
  def self.exp: (Float x) -> Float

  # Calculate hypotenuse of right triangle
  def self.hypot: (Float x, Float y) -> Float

  # Calculate x * 2^n
  def self.ldexp: (Float fraction, Integer exponent) -> Float

  # Calculate natural logarithm
  def self.log: (Float x) -> Float

  # Calculate common logarithm
  def self.log10: (Float x) -> Float

  # Calculate base-2 logarithm
  def self.log2: (Float x) -> Float

  # Calculate sine
  def self.sin: (Float x) -> Float

  # Calculate hyperbolic sine
  def self.sinh: (Float x) -> Float

  # Calculate square root
  def self.sqrt: (Float x) -> Float

  # Calculate tangent
  def self.tan: (Float x) -> Float

  # Calculate hyperbolic tangent
  def self.tanh: (Float x) -> Float

end
